version: 2.1

orbs:
  php: circleci/php@1

executors:
  default:
    docker:
      - image: 'cibuilds/github:latest'

workflows:
  test:
    jobs:
      - php/test:
          name: style-check
          test-command: style:check
